проверка
GiMark00/project15 pull request #1
Opened 2020-12-02 20:16 UTC by GiMark00

Отправляю 15 работу на 1 проверку.

2020-12-03 05:50 UTC, ramiltk53 requested changes
**Здравствуйте!**
В целом неплохая работа, но есть моменты, которые надо будет исправить перед тем, как получится принять работу.
 
**Надо исправить:**

- Для чего установлен в `devDependencies` модуль `css-loader`? Он нам не нужен и его можно удалить. 
- Есть ошибки линтера, для проверки можете использовать `npx eslint .`
- Поле owner в роуте `.post('/cards'` для `createCard` не должен приходить от пользователя, а должен браться из `req.user` , то есть из данный, который мы получим после авторизации пользователя.
- Валидируйте параметры id в роутах `.get(/users/:id` `.delete(/cards/:id`. Для валидации можно использовать `Joi celebrate`.
- В роуте `.post('/signup'` валидацию avatar надо проверять на корректность ссылки. Для этого можно использовать функцию `pattern()`, в который передаётся регулярное выражение. ( Стандартная функция `uri` в `Joi` пропускает невалидные ссылки)
- Для чего в `deleteCard` контроллере метод `.orFail()` используется 2 раза ? Уберите пустой метод. 
- Из-за использования `mongooseHidden` нам не приходят id пользователя, только я не понял преимущество такого подхода. Допустим на фронте я хочу получить всех пользователей, получу список, а как дальше перейти в определённого пользователя, ведь `getSingleUser` делает поиск именно по `req.params.id` , а не email допустим ?
- Отличаются ли `JWT_SECRET`, который в `prod` от `dev-а` ? У меня получилось обращаться к роутам через dev токен.


**Можно лучше:**
- Проверку пароля внутри контроллера createUser можно поместить в Joi валидацию, чтобы некорректные запросы даже не доходили до контрллера.

2020-12-03 15:26 UTC, GiMark00 commented
Отправляю 15 работу на 2 проверку.

2020-12-04 12:52 UTC, ramiltk53 requested changes
Здравствуйте! Спасибо за проделанную работу и изменения.

**Надо исправить:**

- Прошу прощения, сообщил вам на прошлой итерации о валидации `avatar`, но так же надо валидировать `link` в создании карточки.
- Для валидации id в params есть метод лучше. длина id всегда 24 , а так же используются hex значения, поэтому можно использовать конструкцию типа:  `Joi.required().hex().length(24)`, что позволит делать валидацию точнее.
- Если css-loader не нужен на backend , то его надо удалить из проекта ( `devDependencies`  `package.json` ) 
- Укажите доменные имена сервера и фронта в файле README.md

Хорошего дня! Удачи! `:-)`

2020-12-04 16:09 UTC, merged

2020-12-04 16:26 UTC, GiMark00 commented
Отправляю 15 работу на 3 проверку.

2020-12-04 17:56 UTC, ramiltk53 reviewed
Здравствуйте!
Всё супер и работает хорошо. 

**Надо исправить:**

- укажите, пожалуйста, доменное имя сервера и фронта, на котором лежит сайт , иначе я не могу никак посмотреть как работает всё это на сервере.
- Пароль не должен возвращаться в теле ответа при регистрации.

2020-12-04 21:10 UTC, GiMark00 commented
Отправляю 15 работу на 4 проверку.